#!/bin/sh

PWD=`dirname $0`
USERNAME=`whoami`

build() {
	docker pull docker-registry.firevale.com/ass_dev:latest
	docker build ${PWD} -f ${PWD}/Dockerfile -t docker-registry.firevale.com/acs_dev
}

check_build_image() {
	docker images | grep -qi 'docker-registry.firevale.com/acs_dev' || build
}

docker_run() {
	mkdir -p _build/yarn_cache _build/hex_cache
	docker run -it --workdir /code \
								 --privileged \
								 --rm \
								 --expose 4000 \
								 -e "ACS_MYSQL_HOSTNAME=acs_mysql" \
								 -e "ACS_MYSQL_USER=root" \
								 -e "ACS_MYSQL_PASSWORD=firevale" \
								 -e "ACS_REDIS_HOSTNAME=acs_redis" \
								 -e "ACS_ELASTICSEARCH_HOSTNAME=acs_elasticsearch" \
								 -e "ACS_HOST=${USERNAME}.firevale.com" \
								 -e "HEX_MIRROR=https://hexpm.upyun.com" \
								 -p 80:4000 \
								 -v ${PWD}:/code \
								 -v ${PWD}/_build/yarn_cache:/usr/local/share/.cache \
								 -v ${PWD}/_build/hex_cache:/opt/app/.cache \
								 --name acs \
								 --network acs_default \
								 --link acs_mysql:acs_mysql \
								 --link acs_elasticsearch:acs_elasticsearch \
								 --link acs_redis:acs_redis \
								 docker-registry.firevale.com/acs_dev $1
}

console() {
	docker-compose up -d
	check_build_image
	docker_run /start.sh
}

run() {
	mkdir -p _build/yarn_cache _build/hex_cache
	docker-compose up -d
	check_build_image
	docker run -it --workdir /code \
								 --privileged \
								 --rm \
								 --expose 4000 \
								 -e "ACS_MYSQL_HOSTNAME=acs_mysql" \
								 -e "ACS_MYSQL_USER=root" \
								 -e "ACS_MYSQL_PASSWORD=firevale" \
								 -e "ACS_REDIS_HOSTNAME=acs_redis" \
								 -e "ACS_ELASTICSEARCH_HOSTNAME=acs_elasticsearch" \
								 -e "ACS_HOST=${USERNAME}.firevale.com" \
								 -e "HEX_MIRROR=https://hexpm.upyun.com" \
								 -p 80:4000 \
								 -v ${PWD}:/code \
								 -v ${PWD}/_build/yarn_cache:/usr/local/share/.cache \
								 -v ${PWD}/_build/hex_cache:/opt/app/.cache \
								 --name acs \
								 --network acs_default \
								 --link acs_mysql:acs_mysql \
								 --link acs_elasticsearch:acs_elasticsearch \
								 --link acs_redis:acs_redis \
								 docker-registry.firevale.com/acs_dev -c 'iex -S mix phoenix.server'
}

new_for_test() {
	mkdir -p _build/yarn_cache _build/hex_cache
	docker-compose up -d
	check_build_image
	docker run -it --workdir /code \
								 --privileged \
								 --rm \
								 -e "ACS_MYSQL_HOSTNAME=acs_mysql" \
								 -e "ACS_MYSQL_USER=root" \
								 -e "ACS_MYSQL_PASSWORD=firevale" \
								 -e "ACS_REDIS_HOSTNAME=acs_redis" \
								 -e "ACS_ELASTICSEARCH_HOSTNAME=acs_elasticsearch" \
								 -e "HEX_MIRROR=https://hexpm.upyun.com" \
								 -v ${PWD}:/code \
								 -v ${PWD}/_build/yarn_cache:/usr/local/share/.cache \
								 -v ${PWD}/_build/hex_cache:/opt/app/.cache \
								 --name acs \
								 --network acs_default \
								 --link acs_mysql:acs_mysql \
								 --link acs_elasticsearch:acs_elasticsearch \
								 --link acs_redis:acs_redis \
								 docker-registry.firevale.com/acs_dev -c 'mix test'
}

mix() {
	docker ps | awk '{if(NR>1) print $NF}' | grep -e 'acs$' > /dev/null
	if [ $? -eq 0 ]; then
		docker exec acs mix $@
	else
		echo "acs container is not started yet, run ./acs shell or ./acs console to start it first!"
	fi
}

yarn() {
	docker ps | awk '{if(NR>1) print $NF}' | grep -e 'acs$' > /dev/null
	if [ $? -eq 0 ]; then
		docker exec acs /bin/zsh -c "cd /code/static/ && yarn $@ --no-bin-links"
	else
		echo "acs container is not started yet, run ./acs shell or ./acs console to start it first!"
	fi
}

test() {
	docker ps | awk '{if(NR>1) print $NF}' | grep -e 'acs$' > /dev/null
	if [ $? -eq 0 ]; then
		docker exec acs mix test
	else
		new_for_test
	fi
}

shell() {
	docker-compose up -d
	check_build_image
	docker_run
}

update() {
	docker-compose pull
	docker pull docker-registry.firevale.com/ass_dev
	build
}

cd ${PWD}

case "$1" in
	shell)
		shell
		;;
	console)
		console
		;;
	update)
		update
		;;
	run)
		run
		;;
	build)
		build
		;;
	test)
		test
		;;
	mix)
		mix ${@:2}
		;;
	yarn)
		yarn ${@:2}
		;;
	docker_run)
		docker_run ${@:2}
		;;
	*)
		echo "$0 COMMAND" && echo "volumn from local: $PWD"
		echo "COMMAND: shell -- run shell command in acs container"
		echo "COMMAND: update -- update docker images used by ACS server"
		;;
esac
