#!/bin/sh

for p in extcp exes exsm exredis excache exutils exsdks exwcp exservice exmail
do
   git subtree pull --prefix=apps/$p $p acs --squash
   git subtree push --prefix=apps/$p $p acs --squash
   git subtree split --rejoin --prefix=apps/$p  
done